<a href="https://colab.research.google.com/github/Kunamathrusri/AIML/blob/main/Autophobia_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv("/content/sample_data/autophobia_realistic (1).csv")

In [ ]:
df.head()

gender live_alone hours_spent_alone activities_when_alone  \
0    Male         No  Less than 1 hour       Watch TV/YouTub   
1  Female         No         1–3 hours      Use social media   
2  Female         No         1–3 hours              Exercise   
3  Female         No         1–3 hours      Use social media   
4  Female         No         1–3 hours      Use social media   

  panic_attack_anxiety avoid_alone  age  anxious_alone  \
0                   No          No   20              3   
1                  Yes         Yes   20              3   
2                   No   Sometimes   20              1   
3                  Yes          No   20              4   
4                  Yes          No   20              5   

   emotionally_distressed  abondoned  unsafe_uneasy  constant_contact  \
0                       1          1              1                 2   
1                       3          4              1                 4   
2                       1          3              4                 4   
3                       3          4              5                 4   
4                       4          5              5                 4   

   TV/music/phone  sleep_poorly  going_out_staying_home  someone_nearby  \
0               5             1                       1               1   
1               5             3                       4               5   
2               2             2                       1               4   
3               4             2                       4               3   
4               5             1                       4               3   

   panic_if_cant_reach  autophobia  
0                    2           0  
1                    3           1  
2                    1           0  
3                    2           0  
4                    2           0

In [ ]:
df.shape

(500, 18)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   gender                  500 non-null    object
 1   live_alone              500 non-null    object
 2   hours_spent_alone       500 non-null    object
 3   activities_when_alone   500 non-null    object
 4   panic_attack_anxiety    500 non-null    object
 5   avoid_alone             500 non-null    object
 6   age                     500 non-null    int64 
 7   anxious_alone           500 non-null    int64 
 8   emotionally_distressed  500 non-null    int64 
 9   abondoned               500 non-null    int64 
 10  unsafe_uneasy           500 non-null    int64 
 11  constant_contact        500 non-null    int64 
 12  TV/music/phone          500 non-null    int64 
 13  sleep_poorly            500 non-null    int64 
 14  going_out_staying_home  500 non-null    int64 
 15  someon

In [ ]:
df['gender'] = df['gender'].map({'Male': 0, 'Female': 1})

In [ ]:
df.head()

gender live_alone hours_spent_alone activities_when_alone  \
0       0         No  Less than 1 hour       Watch TV/YouTub   
1       1         No         1–3 hours      Use social media   
2       1         No         1–3 hours              Exercise   
3       1         No         1–3 hours      Use social media   
4       1         No         1–3 hours      Use social media   

  panic_attack_anxiety avoid_alone  age  anxious_alone  \
0                   No          No   20              3   
1                  Yes         Yes   20              3   
2                   No   Sometimes   20              1   
3                  Yes          No   20              4   
4                  Yes          No   20              5   

   emotionally_distressed  abondoned  unsafe_uneasy  constant_contact  \
0                       1          1              1                 2   
1                       3          4              1                 4   
2                       1          3              4                 4   
3                       3          4              5                 4   
4                       4          5              5                 4   

   TV/music/phone  sleep_poorly  going_out_staying_home  someone_nearby  \
0               5             1                       1               1   
1               5             3                       4               5   
2               2             2                       1               4   
3               4             2                       4               3   
4               5             1                       4               3   

   panic_if_cant_reach  autophobia  
0                    2           0  
1                    3           1  
2                    1           0  
3                    2           0  
4                    2           0

In [ ]:
df['live_alone']=df['live_alone'].map({'Yes':1,'No':0})

In [ ]:
df.head()

gender  live_alone hours_spent_alone activities_when_alone  \
0       0           0  Less than 1 hour       Watch TV/YouTub   
1       1           0         1–3 hours      Use social media   
2       1           0         1–3 hours              Exercise   
3       1           0         1–3 hours      Use social media   
4       1           0         1–3 hours      Use social media   

  panic_attack_anxiety avoid_alone  age  anxious_alone  \
0                   No          No   20              3   
1                  Yes         Yes   20              3   
2                   No   Sometimes   20              1   
3                  Yes          No   20              4   
4                  Yes          No   20              5   

   emotionally_distressed  abondoned  unsafe_uneasy  constant_contact  \
0                       1          1              1                 2   
1                       3          4              1                 4   
2                       1          3              4                 4   
3                       3          4              5                 4   
4                       4          5              5                 4   

   TV/music/phone  sleep_poorly  going_out_staying_home  someone_nearby  \
0               5             1                       1               1   
1               5             3                       4               5   
2               2             2                       1               4   
3               4             2                       4               3   
4               5             1                       4               3   

   panic_if_cant_reach  autophobia  
0                    2           0  
1                    3           1  
2                    1           0  
3                    2           0  
4                    2           0

In [ ]:
for col in df.columns:
    print(f"--- {col} ---")
    print(df[col].unique())
    print()

--- gender ---
[0 1]

--- live_alone ---
[0 1]

--- hours_spent_alone ---
['Less than 1 hour' '1–3 hours' 'More than 6 hours' '3–6 hours']

--- activities_when_alone ---
['Watch TV/YouTub' 'Use social media' 'Exercise' 'Work or study'
 'Try to sleep']

--- panic_attack_anxiety ---
['No' 'Yes']

--- avoid_alone ---
['No' 'Yes' 'Sometimes']

--- age ---
[20 21 18]

--- anxious_alone ---
[3 1 4 5 2 0]

--- emotionally_distressed ---
[1 3 4 2 5 0]

--- abondoned ---
[1 4 3 5 2 0]

--- unsafe_uneasy ---
[1 4 5 3 2 0]

--- constant_contact ---
[2 4 1 3 5 0]

--- TV/music/phone ---
[5 2 4 1 3 0]

--- sleep_poorly ---
[1 3 2 5 0 4]

--- going_out_staying_home ---
[1 4 3 5 2 0]

--- someone_nearby ---
[1 5 4 3 2 0]

--- panic_if_cant_reach ---
[2 3 1 0 4]

--- autophobia ---
[0 1]



In [ ]:
columns_to_remove = [
    'panic_if_cant_reach',
    'anxious_alone',
    'panic_attack_anxiety',
    'emotionally_distressed',
    'sleep_poorly'
]

In [ ]:
df.drop(columns=columns_to_remove, inplace=True)

df.head()

gender  live_alone hours_spent_alone activities_when_alone avoid_alone  \
0       0           0  Less than 1 hour       Watch TV/YouTub          No   
1       1           0         1–3 hours      Use social media         Yes   
2       1           0         1–3 hours              Exercise   Sometimes   
3       1           0         1–3 hours      Use social media          No   
4       1           0         1–3 hours      Use social media          No   

   age  abondoned  unsafe_uneasy  constant_contact  TV/music/phone  \
0   20          1              1                 2               5   
1   20          4              1                 4               5   
2   20          3              4                 4               2   
3   20          4              5                 4               4   
4   20          5              5                 4               5   

   going_out_staying_home  someone_nearby  autophobia  
0                       1               1           0  
1                       4               5           1  
2                       1               4           0  
3                       4               3           0  
4                       4               3           0

In [ ]:
df_encoded = pd.get_dummies(df, columns=['hours_spent_alone','activities_when_alone','avoid_alone'])

In [ ]:
df_encoded.head()

gender  live_alone  age  abondoned  unsafe_uneasy  constant_contact  \
0       0           0   20          1              1                 2   
1       1           0   20          4              1                 4   
2       1           0   20          3              4                 4   
3       1           0   20          4              5                 4   
4       1           0   20          5              5                 4   

   TV/music/phone  going_out_staying_home  someone_nearby  autophobia  ...  \
0               5                       1               1           0  ...   
1               5                       4               5           1  ...   
2               2                       1               4           0  ...   
3               4                       4               3           0  ...   
4               5                       4               3           0  ...   

   hours_spent_alone_Less than 1 hour  hours_spent_alone_More than 6 hours  \
0                                True                                False   
1                               False                                False   
2                               False                                False   
3                               False                                False   
4                               False                                False   

   activities_when_alone_Exercise  activities_when_alone_Try to sleep  \
0                           False                               False   
1                           False                               False   
2                            True                               False   
3                           False                               False   
4                           False                               False   

   activities_when_alone_Use social media  \
0                                   False   
1                                    True   
2                                   False   
3                                    True   
4                                    True   

   activities_when_alone_Watch TV/YouTub  activities_when_alone_Work or study  \
0                                   True                                False   
1                                  False                                False   
2                                  False                                False   
3                                  False                                False   
4                                  False                                False   

   avoid_alone_No  avoid_alone_Sometimes  avoid_alone_Yes  
0            True                  False            False  
1           False                  False             True  
2           False                   True            False  
3            True                  False            False  
4            True                  False            False  

[5 rows x 22 columns]

In [ ]:
for col in df_encoded.columns:
    if df_encoded[col].dtype == 'bool':
        df_encoded[col] = df_encoded[col].astype(int)

In [ ]:
df_encoded.shape

(500, 22)

In [ ]:
df_encoded.shape

(500, 22)

In [ ]:
df_encoded.head()

gender  live_alone  age  abondoned  unsafe_uneasy  constant_contact  \
0       0           0   20          1              1                 2   
1       1           0   20          4              1                 4   
2       1           0   20          3              4                 4   
3       1           0   20          4              5                 4   
4       1           0   20          5              5                 4   

   TV/music/phone  going_out_staying_home  someone_nearby  autophobia  ...  \
0               5                       1               1           0  ...   
1               5                       4               5           1  ...   
2               2                       1               4           0  ...   
3               4                       4               3           0  ...   
4               5                       4               3           0  ...   

   hours_spent_alone_Less than 1 hour  hours_spent_alone_More than 6 hours  \
0                                   1                                    0   
1                                   0                                    0   
2                                   0                                    0   
3                                   0                                    0   
4                                   0                                    0   

   activities_when_alone_Exercise  activities_when_alone_Try to sleep  \
0                               0                                   0   
1                               0                                   0   
2                               1                                   0   
3                               0                                   0   
4                               0                                   0   

   activities_when_alone_Use social media  \
0                                       0   
1                                       1   
2                                       0   
3                                       1   
4                                       1   

   activities_when_alone_Watch TV/YouTub  activities_when_alone_Work or study  \
0                                      1                                    0   
1                                      0                                    0   
2                                      0                                    0   
3                                      0                                    0   
4                                      0                                    0   

   avoid_alone_No  avoid_alone_Sometimes  avoid_alone_Yes  
0               1                      0                0  
1               0                      0                1  
2               0                      1                0  
3               1                      0                0  
4               1                      0                0  

[5 rows x 22 columns]

In [ ]:
# Replace 'autophobia_present' with your actual target column
X = df_encoded.drop(columns=['autophobia'])
y = df_encoded['autophobia']


In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)


In [ ]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)


RandomForestClassifier(random_state=42)

In [ ]:
y_pred = rf_model.predict(X_test)


In [ ]:
print(y_pred)

[1 0 1 0 0 1 0 0 1 1 1 0 0 1 1 0 1 0 1 0 0 0 1 1 0 1 0 0 1 1 1 1 0 0 1 0 1
 1 0 1 0 1 0 1 0 0 0 0 1 0 0 0 1 1 0 0 0 1 1 1 1 0 0 0 1 1 0 1 1 1 1 1 1 1
 0 1 0 0 0 0 1 1 0 1 1 0 0 1 1 0 0 0 0 1 1 1 1 1 1 0]


In [ ]:
y_proba = rf_model.predict_proba(X_test)


In [ ]:
print(y_proba)

[[0.14       0.86      ]
 [0.95       0.05      ]
 [0.02       0.98      ]
 [0.83       0.17      ]
 [0.93       0.07      ]
 [0.015      0.985     ]
 [0.98       0.02      ]
 [0.85       0.15      ]
 [0.01       0.99      ]
 [0.13       0.87      ]
 [0.03529762 0.96470238]
 [0.9        0.1       ]
 [0.95       0.05      ]
 [0.06666667 0.93333333]
 [0.09333333 0.90666667]
 [0.765      0.235     ]
 [0.         1.        ]
 [0.96       0.04      ]
 [0.046      0.954     ]
 [0.96       0.04      ]
 [0.92       0.08      ]
 [0.94       0.06      ]
 [0.04666667 0.95333333]
 [0.         1.        ]
 [0.92       0.08      ]
 [0.1        0.9       ]
 [0.97       0.03      ]
 [0.98       0.02      ]
 [0.         1.        ]
 [0.3825     0.6175    ]
 [0.39333333 0.60666667]
 [0.03       0.97      ]
 [1.         0.        ]
 [0.93       0.07      ]
 [0.02       0.98      ]
 [0.9        0.1       ]
 [0.         1.        ]
 [0.02261905 0.97738095]
 [0.83       0.17      ]
 [0.00892857 0.99107143]


In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report, roc_auc_score, roc_curve


In [ ]:
print("Accuracy:", accuracy_score(y_test, y_pred))


Accuracy: 0.93


In [ ]:
df_encoded.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 22 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   gender                                  500 non-null    int64
 1   live_alone                              500 non-null    int64
 2   age                                     500 non-null    int64
 3   abondoned                               500 non-null    int64
 4   unsafe_uneasy                           500 non-null    int64
 5   constant_contact                        500 non-null    int64
 6   TV/music/phone                          500 non-null    int64
 7   going_out_staying_home                  500 non-null    int64
 8   someone_nearby                          500 non-null    int64
 9   autophobia                              500 non-null    int64
 10  hours_spent_alone_1–3 hours             500 non-null    int64
 11  hours_spent_alone_3

In [ ]:
test_input = {
    'gender': 0,                         # Male
    'live_alone': 1,                     # Lives alone
    'age': 27,
    'abondoned': 1,
    'unsafe_uneasy': 1,
    'constant_contact': 2,
    'TV/music/phone': 3,
    'going_out_staying_home': 2,
    'someone_nearby': 1,
    'hours_spent_alone_1–3 hours': 0,
    'hours_spent_alone_3–6 hours': 1,
    'hours_spent_alone_Less than 1 hour': 0,
    'hours_spent_alone_More than 6 hours': 0,
    'activities_when_alone_Exercise': 0,
    'activities_when_alone_Try to sleep': 0,
    'activities_when_alone_Use social media': 1,
    'activities_when_alone_Watch TV/YouTub': 0,
    'activities_when_alone_Work or study': 0,
    'avoid_alone_No': 0,
    'avoid_alone_Sometimes': 1,
    'avoid_alone_Yes': 0
}


In [ ]:

test_df = pd.DataFrame([test_input])

prediction = rf_model.predict(test_df)
probability = rf_model.predict_proba(test_df)

print("Predicted Autophobia:", prediction[0])       # 0 or 1
print("Probability [No, Yes]:", probability[0])     # Probabilities




Predicted Autophobia: 0
Probability [No, Yes]: [0.95 0.05]


In [ ]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(rf_model, X, y, cv=5)
print("Average CV Accuracy:", scores.mean())


Average CV Accuracy: 0.9279999999999999


In [ ]:
import matplotlib.pyplot as plt
importances = rf_model.feature_importances_
print(importances)
#plt.barh(X.columns, importances)

[0.02851208 0.00537091 0.03087121 0.17770193 0.06540537 0.08322491
 0.26901205 0.05342603 0.10439844 0.01087961 0.00686866 0.0143048
 0.04451822 0.00493245 0.00614096 0.01087876 0.02538995 0.02054616
 0.01429427 0.01065429 0.01266893]


In [ ]:
def calculate_autophobia_severity_normalized(input_data, feature_importances, feature_names, max_feature_values):
    weighted_sum = 0
    max_weighted_sum = 0

    for feat, imp in zip(feature_names, feature_importances):
        value = input_data.get(feat, 0)
        max_val = max_feature_values.get(feat, 1)

        weighted_sum += value * imp
        max_weighted_sum += max_val * imp

    normalized_score = (weighted_sum / max_weighted_sum) * 100
    return int(round(normalized_score))



In [ ]:
test_input = {
    'gender': 0,                         # Male
    'live_alone': 1,                     # Lives alone
    'age': 27,
    'abondoned': 1,
    'unsafe_uneasy': 1,
    'constant_contact': 2,
    'TV/music/phone': 3,
    'going_out_staying_home': 2,
    'someone_nearby': 1,
    'hours_spent_alone_1–3 hours': 0,
    'hours_spent_alone_3–6 hours': 1,
    'hours_spent_alone_Less than 1 hour': 0,
    'hours_spent_alone_More than 6 hours': 0,
    'activities_when_alone_Exercise': 0,
    'activities_when_alone_Try to sleep': 0,
    'activities_when_alone_Use social media': 1,
    'activities_when_alone_Watch TV/YouTub': 0,
    'activities_when_alone_Work or study': 0,
    'avoid_alone_No': 0,
    'avoid_alone_Sometimes': 1,
    'avoid_alone_Yes': 0
}
test_df = pd.DataFrame([test_input])

prediction = rf_model.predict(test_df)
probability = rf_model.predict_proba(test_df)

print("Predicted Autophobia:", prediction[0])       # 0 or 1
test_input = {
    'gender': 0,                         # Male
    'live_alone': 1,                     # Lives alone
    'age': 27,
    'abondoned': 1,
    'unsafe_uneasy': 1,
    'constant_contact': 2,
    'TV/music/phone': 3,
    'going_out_staying_home': 2,
    'someone_nearby': 1,
    'hours_spent_alone_1–3 hours': 0,
    'hours_spent_alone_3–6 hours': 1,
    'hours_spent_alone_Less than 1 hour': 0,
    'hours_spent_alone_More than 6 hours': 0,
    'activities_when_alone_Exercise': 0,
    'activities_when_alone_Try to sleep': 0,
    'activities_when_alone_Use social media': 1,
    'activities_when_alone_Watch TV/YouTub': 0,
    'activities_when_alone_Work or study': 0,
    'avoid_alone_No': 0,
    'avoid_alone_Sometimes': 1,
    'avoid_alone_Yes': 0
}
test_df = pd.DataFrame([test_input])

prediction = rf_model.predict(test_df)
probability = rf_model.predict_proba(test_df)

print("Predicted Autophobia:", prediction[0])       # 0 or 1
print("Probability [No, Yes]:", probability[0])     # Probabilities
if prediction[0]!=0:
    feature_names = X.columns.tolist()
    feature_importances = rf_model.feature_importances_.tolist()
    # Assume df is your full training dataset used to train the model
    # It should contain only the features (no target column)

    max_feature_values = df.max().to_dict()

    severity = calculate_autophobia_severity_normalized(test_input, feature_importances, feature_names,max_feature_values)
    print(f"Predicted Autophobia Severity Score: {severity}/100")
# It should contain only the features (no target column)

    max_feature_values = df.max().to_dict()

    severity = calculate_autophobia_severity_normalized(test_input, feature_importances, feature_names,max_feature_values)
    print(f"Predicted Autophobia Severity Score: {severity}/100")

Predicted Autophobia: 0
Predicted Autophobia: 0
Probability [No, Yes]: [0.95 0.05]


In [ ]:
test_input = {
    'gender': 1,                         # Female
    'live_alone': 0,                     # Doesn't live alone
    'age': 20,
    'abondoned': 1,                      # Coded binary
    'unsafe_uneasy': 1,
    'constant_contact': 4,
    'TV/music/phone': 5,
    'going_out_staying_home': 4,
    'someone_nearby': 5,
    'hours_spent_alone_1–3 hours': 1,
    'hours_spent_alone_3–6 hours': 0,
    'hours_spent_alone_Less than 1 hour': 0,
    'hours_spent_alone_More than 6 hours': 0,
    'activities_when_alone_Exercise': 0,
    'activities_when_alone_Try to sleep': 0,
    'activities_when_alone_Use social media': 1,
    'activities_when_alone_Watch TV/YouTub': 0,
    'activities_when_alone_Work or study': 0,
    'avoid_alone_No': 0,
    'avoid_alone_Sometimes': 0,
    'avoid_alone_Yes': 1
}


test_df = pd.DataFrame([test_input])

prediction = rf_model.predict(test_df)
probability = rf_model.predict_proba(test_df)

print("Predicted Autophobia:", prediction[0])       # 0 or 1
print("Probability [No, Yes]:", probability[0])     # Probabilities
if prediction[0]!=0:
    feature_names = X.columns.tolist()
    feature_importances = rf_model.feature_importances_.tolist()
    # Assume df is your full training dataset used to train the model
    # It should contain only the features (no target column)

    max_feature_values = df.max().to_dict()

    severity = calculate_autophobia_severity_normalized(test_input, feature_importances, feature_names,max_feature_values)
    print(f"Predicted Autophobia Severity Score: {severity}/100")


Predicted Autophobia: 1
Probability [No, Yes]: [0.49 0.51]
Predicted Autophobia Severity Score: 72/100
